# Generated by Django 2.2.4 on 2020-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
